In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
stop_90 = pd.read_csv('data/stop_90_quat.csv', sep=",")
stop_90_without_speed = stop_90
stop_90_without_speed

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,-0.199,0.634,0.189,-0.095,0.553,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.127,-0.027,2.241,0.199,0.037,-0.025,-0.004,0.999
1,-0.199,0.635,0.189,-0.095,0.552,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.033,2.242,0.199,0.030,-0.027,0.001,0.999
2,-0.199,0.634,0.189,-0.095,0.552,0.805,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.038,2.242,0.198,0.030,-0.033,0.003,0.999
3,-0.199,0.634,0.189,-0.095,0.552,0.805,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.041,2.241,0.197,0.031,-0.035,0.006,0.999
4,-0.199,0.635,0.189,-0.095,0.552,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.039,2.241,0.197,0.028,-0.037,0.002,0.999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.202,0.631,0.222,-0.125,0.559,0.788,0.225,0.193,0.627,0.216,...,-0.554,-0.809,0.174,-0.054,2.245,0.190,0.014,-0.021,0.059,0.998
2396,-0.202,0.631,0.222,-0.125,0.559,0.788,0.224,0.193,0.627,0.216,...,-0.554,-0.809,0.174,-0.045,2.246,0.189,0.011,-0.012,0.037,0.999
2397,-0.202,0.631,0.222,-0.125,0.559,0.788,0.224,0.193,0.627,0.216,...,-0.554,-0.809,0.174,-0.035,2.248,0.189,0.009,-0.003,0.014,1.000
2398,-0.202,0.631,0.222,-0.125,0.559,0.788,0.224,0.193,0.626,0.216,...,-0.554,-0.809,0.174,-0.025,2.248,0.188,0.008,0.005,-0.010,1.000
2399,-0.202,0.631,0.222,-0.125,0.559,0.788,0.224,0.193,0.626,0.217,...,-0.554,-0.809,0.174,-0.016,2.248,0.189,0.006,0.013,-0.031,0.999

In [3]:
euler=stop_90[['e_r_x','e_r_y','e_r_z','e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
euler

      e_r_x  e_r_y  e_r_z  e_r_w  d_r_x  d_r_y  d_r_z  d_r_w
0    -0.095  0.553  0.804  0.196 -0.032 -0.556 -0.821  0.127
1    -0.095  0.552  0.804  0.196 -0.032 -0.556 -0.821  0.128
2    -0.095  0.552  0.805  0.196 -0.032 -0.556 -0.821  0.128
3    -0.095  0.552  0.805  0.196 -0.032 -0.556 -0.821  0.128
4    -0.095  0.552  0.804  0.196 -0.031 -0.556 -0.821  0.128
...     ...    ...    ...    ...    ...    ...    ...    ...
2395 -0.125  0.559  0.788  0.225 -0.089 -0.554 -0.809  0.174
2396 -0.125  0.559  0.788  0.224 -0.089 -0.554 -0.809  0.174
2397 -0.125  0.559  0.788  0.224 -0.089 -0.554 -0.809  0.174
2398 -0.125  0.559  0.788  0.224 -0.089 -0.554 -0.809  0.174
2399 -0.125  0.559  0.788  0.224 -0.089 -0.554 -0.809  0.174

[2400 rows x 8 columns]

In [4]:
stop_90_diff = stop_90_without_speed.diff()
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.001,0.0,0.0,-0.001,0.000,0.000,0.0,0.000,0.000,...,0.0,0.0,0.001,-0.006,0.001,0.000,-0.007,-0.002,0.005,0.000
2,0.0,-0.001,0.0,0.0,0.000,0.001,0.000,0.0,0.000,0.000,...,0.0,0.0,0.000,-0.005,0.000,-0.001,0.000,-0.006,0.002,0.000
3,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,...,0.0,0.0,0.000,-0.003,-0.001,-0.001,0.001,-0.002,0.003,0.000
4,0.0,0.001,0.0,0.0,0.000,-0.001,0.000,0.0,0.000,0.000,...,0.0,0.0,0.000,0.002,0.000,0.000,-0.003,-0.002,-0.004,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.0,0.000,0.0,0.0,-0.001,0.000,0.001,0.0,0.000,-0.001,...,0.0,0.0,0.000,0.008,0.002,-0.002,-0.004,0.010,-0.021,0.002
2396,0.0,0.000,0.0,0.0,0.000,0.000,-0.001,0.0,0.000,0.000,...,0.0,0.0,0.000,0.009,0.001,-0.001,-0.003,0.009,-0.022,0.001
2397,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.000,...,0.0,0.0,0.000,0.010,0.002,0.000,-0.002,0.009,-0.023,0.001
2398,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,-0.001,0.000,...,0.0,0.0,0.000,0.010,0.000,-0.001,-0.001,0.008,-0.024,0.000
2399,0.0,0.000,0.0,0.0,0.000,0.000,0.000,0.0,0.000,0.001,...,0.0,0.0,0.000,0.009,0.000,0.001,-0.002,0.008,-0.021,-0.001

In [5]:
stop_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.095,0.553,0.804,0.196,NaN,NaN,NaN,...,-0.556,-0.821,0.127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.001,0.0,-0.095,0.552,0.804,0.196,0.0,0.000,0.000,...,-0.556,-0.821,0.128,-0.006,0.001,0.000,-0.007,-0.002,0.005,0.000
2,0.0,-0.001,0.0,-0.095,0.552,0.805,0.196,0.0,0.000,0.000,...,-0.556,-0.821,0.128,-0.005,0.000,-0.001,0.000,-0.006,0.002,0.000
3,0.0,0.000,0.0,-0.095,0.552,0.805,0.196,0.0,0.000,0.000,...,-0.556,-0.821,0.128,-0.003,-0.001,-0.001,0.001,-0.002,0.003,0.000
4,0.0,0.001,0.0,-0.095,0.552,0.804,0.196,0.0,0.000,0.000,...,-0.556,-0.821,0.128,0.002,0.000,0.000,-0.003,-0.002,-0.004,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.0,0.000,0.0,-0.125,0.559,0.788,0.225,0.0,0.000,-0.001,...,-0.554,-0.809,0.174,0.008,0.002,-0.002,-0.004,0.010,-0.021,0.002
2396,0.0,0.000,0.0,-0.125,0.559,0.788,0.224,0.0,0.000,0.000,...,-0.554,-0.809,0.174,0.009,0.001,-0.001,-0.003,0.009,-0.022,0.001
2397,0.0,0.000,0.0,-0.125,0.559,0.788,0.224,0.0,0.000,0.000,...,-0.554,-0.809,0.174,0.010,0.002,0.000,-0.002,0.009,-0.023,0.001
2398,0.0,0.000,0.0,-0.125,0.559,0.788,0.224,0.0,-0.001,0.000,...,-0.554,-0.809,0.174,0.010,0.000,-0.001,-0.001,0.008,-0.024,0.000
2399,0.0,0.000,0.0,-0.125,0.559,0.788,0.224,0.0,0.000,0.001,...,-0.554,-0.809,0.174,0.009,0.000,0.001,-0.002,0.008,-0.021,-0.001

In [6]:
forward_90 = pd.read_csv('data/0_90_quat.csv', sep=",")
forward_90_without_speed = forward_90[forward_90.columns[:-1]]
euler_forward_90=forward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
forward_90_diff = forward_90_without_speed.diff()
forward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_forward_90
forward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.125,0.559,0.788,0.224,NaN,NaN,NaN,-0.089,-0.554,-0.809,0.174,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.005,-0.001,0.001,0.002,0.004,-0.009
2,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.007,-0.001,0.001,0.001,0.006,-0.010
3,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.004,0.001,0.001,-0.003,0.001,0.004
4,0.001,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,-0.001,0.001,-0.001,-0.004,-0.005,0.008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.000,0.000,-0.001,-0.104,0.538,0.811,0.204,-0.008,-0.005,-0.081,-0.038,-0.552,-0.823,0.132,0.031,-0.003,-0.007,0.000,-0.006,0.000
2396,0.000,0.001,0.001,-0.079,0.504,0.842,0.178,0.001,-0.001,-0.004,-0.038,-0.558,-0.818,0.132,0.033,0.000,-0.009,0.009,-0.007,0.001
2397,-0.004,-0.001,0.020,-0.073,0.311,0.934,0.158,0.000,0.001,0.003,-0.039,-0.553,-0.822,0.125,0.017,-0.002,-0.009,0.008,0.005,-0.014
2398,0.023,0.019,0.141,-0.007,0.477,0.866,0.153,0.002,0.001,0.000,-0.039,-0.554,-0.823,0.123,0.006,0.004,-0.003,-0.002,0.004,0.005
2399,-0.008,0.020,0.148,-0.012,0.608,0.778,0.154,-0.001,-0.001,0.000,-0.040,-0.554,-0.822,0.124,-0.008,0.000,0.010,-0.014,0.002,0.003

In [7]:
left_90 = pd.read_csv('data/90_90_quat.csv', sep=",")
left_90_without_speed =left_90
euler_left_90=left_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
left_90_diff =left_90_without_speed.diff()
left_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_left_90
left_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.018,0.632,0.761,0.148,NaN,NaN,NaN,...,-0.554,-0.822,0.127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.022,-0.015,-0.069,-0.002,0.611,0.775,0.160,-0.001,0.000,0.001,...,-0.550,-0.825,0.128,-0.039,-0.002,0.022,0.008,-0.001,0.014,0.000
2,0.001,-0.021,-0.123,0.008,0.593,0.797,0.110,0.001,0.000,0.001,...,-0.548,-0.826,0.130,-0.039,0.000,0.007,-0.001,0.006,0.005,0.000
3,0.001,-0.010,-0.120,0.018,0.565,0.816,0.123,-0.001,-0.002,0.000,...,-0.544,-0.828,0.132,-0.037,-0.008,-0.003,0.021,0.006,0.005,0.001
4,0.004,-0.003,-0.080,-0.006,0.571,0.807,0.150,0.005,-0.001,0.001,...,-0.511,-0.846,0.145,-0.051,-0.006,-0.019,-0.011,0.007,0.003,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.001,-0.001,0.000,-0.535,0.329,0.612,0.481,-0.048,0.004,-0.004,...,0.618,0.458,0.398,-0.018,-0.002,0.025,-0.004,-0.005,-0.012,-0.006
2396,0.000,0.001,0.001,-0.536,0.327,0.615,0.477,0.100,-0.046,-0.026,...,0.545,0.525,0.351,-0.013,0.004,0.031,0.013,-0.007,-0.004,-0.007
2397,0.000,0.000,0.000,-0.535,0.326,0.618,0.475,0.172,-0.038,-0.036,...,0.518,0.612,0.294,0.002,0.001,0.045,0.003,-0.004,-0.014,-0.003
2398,-0.001,0.000,0.000,-0.535,0.325,0.619,0.474,0.120,-0.012,-0.027,...,0.501,0.638,0.290,0.005,-0.003,0.033,0.003,-0.005,-0.012,-0.006
2399,0.001,0.001,0.001,-0.532,0.322,0.620,0.478,0.060,-0.001,-0.011,...,0.518,0.658,0.252,0.007,-0.003,0.043,0.005,-0.005,-0.014,-0.006

In [8]:
backward_90 = pd.read_csv('data/180_90_quat.csv', sep=",")
backward_90_without_speed = backward_90
euler_backward_90=backward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
backward_90_diff = backward_90_without_speed.diff()
backward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_backward_90
backward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.567,0.292,0.623,0.453,NaN,NaN,NaN,...,0.516,0.657,0.260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.034,0.023,0.005,-0.568,0.094,0.705,0.414,-0.003,0.000,0.002,...,0.514,0.658,0.257,0.023,-0.001,0.020,0.004,0.012,-0.001,0.013
2,-0.133,0.018,0.016,-0.564,0.241,0.622,0.486,-0.001,0.001,0.000,...,0.512,0.659,0.258,0.010,0.007,-0.002,-0.005,-0.005,0.009,-0.005
3,-0.150,0.023,-0.032,-0.552,0.293,0.512,0.590,0.000,0.000,0.000,...,0.514,0.657,0.257,-0.001,0.000,-0.010,-0.008,0.000,0.000,0.000
4,-0.065,0.012,0.006,-0.503,0.360,0.525,0.584,0.000,-0.001,0.000,...,0.513,0.659,0.254,-0.010,-0.001,-0.015,-0.011,0.003,-0.001,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.006,0.005,-0.024,-0.945,-0.181,0.068,0.263,0.000,-0.002,-0.003,...,0.225,0.161,0.489,-0.003,0.010,0.017,-0.008,0.000,0.000,-0.014
2396,0.008,0.006,-0.143,-0.868,-0.204,0.027,0.452,-0.001,0.001,0.000,...,0.226,0.160,0.489,0.009,0.007,0.003,0.011,0.000,0.013,-0.001
2397,0.001,0.025,-0.215,-0.780,-0.175,-0.043,0.599,0.000,0.000,-0.001,...,0.228,0.160,0.489,0.024,-0.004,-0.016,0.004,0.000,0.007,0.009
2398,-0.006,0.001,-0.037,-0.785,-0.175,-0.016,0.594,0.000,0.001,0.000,...,0.231,0.160,0.490,0.032,-0.003,-0.030,0.000,0.000,0.003,0.008
2399,-0.003,-0.010,0.042,-0.779,-0.174,-0.026,0.602,0.000,0.000,-0.001,...,0.233,0.162,0.483,0.033,-0.002,-0.023,0.003,0.000,-0.007,0.009

In [9]:
right_90 = pd.read_csv('data/270_90_quat.csv', sep=",")
right_90_without_speed = right_90
euler_right_90=right_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
right_90_diff = right_90_without_speed.diff()
right_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_right_90
right_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.793,-0.163,-0.020,0.587,NaN,NaN,NaN,...,0.234,0.166,0.481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.010,-0.012,0.112,-0.810,-0.153,0.005,0.566,0.000,-0.001,0.001,...,0.234,0.174,0.477,0.030,0.005,0.020,0.003,0.000,0.000,-0.003
2,-0.016,-0.002,0.105,-0.825,-0.133,0.032,0.548,-0.001,-0.001,0.001,...,0.225,0.171,0.464,0.024,0.007,0.037,0.003,0.000,0.000,-0.010
3,-0.004,-0.004,0.034,-0.802,-0.153,0.042,0.576,-0.001,-0.003,0.000,...,0.193,0.137,0.396,0.018,-0.001,0.042,0.007,0.000,0.010,-0.016
4,0.002,0.001,-0.001,-0.821,-0.144,0.044,0.551,-0.019,0.028,-0.076,...,0.165,0.094,0.283,0.007,0.015,0.019,0.018,0.000,-0.002,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.109,0.020,-0.022,-0.698,-0.411,-0.516,0.281,0.000,0.000,0.001,...,-0.140,-0.382,0.543,-0.001,0.007,0.010,-0.007,-0.002,0.017,0.002
2396,0.177,0.021,-0.016,-0.589,-0.520,-0.503,0.360,0.001,-0.001,0.000,...,-0.136,-0.384,0.543,0.023,-0.001,0.016,0.007,-0.005,0.014,0.006
2397,0.074,0.007,-0.018,-0.618,-0.485,-0.506,0.357,0.001,0.000,0.000,...,-0.130,-0.383,0.541,0.036,-0.006,0.018,0.007,-0.003,0.011,0.002
2398,-0.073,-0.017,0.032,-0.561,-0.518,-0.535,0.362,0.001,0.000,-0.001,...,-0.126,-0.385,0.540,0.049,-0.007,0.028,0.010,-0.003,0.006,0.004
2399,-0.130,-0.019,0.014,-0.614,-0.497,-0.514,0.335,0.000,-0.001,0.000,...,-0.132,-0.385,0.534,0.041,-0.007,0.040,0.016,-0.008,0.001,0.008

In [10]:
stop_90_diff.to_csv('stop_90_diff_quat.csv', index=False, header=True)
forward_90_diff.to_csv('0_90_diff_quat.csv', index=False, header=True)
left_90_diff.to_csv('90_90_diff_quat.csv', index=False, header=True)
backward_90_diff.to_csv('180_90_diff_quat.csv', index=False, header=True)
right_90_diff.to_csv('270_90_diff_quat.csv', index=False, header=True)