In [9]:
from pathlib import Path
import numpy as np
import pandas as pd

In [10]:
stop_90 = pd.read_csv('data/stop_90_quat.csv', sep=",")
stop_90_without_speed = stop_90[stop_90.columns[:-1]]
stop_90_without_speed

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,-0.001,0.0,0.0,0.0,0.001,0.000000,0.000000,-0.001,0.000,0.000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.000,0.0
1,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.000,0.000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.001,0.000,...,0.000000,0.000000,-0.001000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.000,0.000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
4,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.000,-0.001,...,0.000000,0.000000,-0.001000,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,-0.0,-0.0,0.000,0.088369,-0.996088,0.000,0.000,-0.000,...,0.000000,0.088369,-0.996088,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71984,0.000,0.0,-0.0,-0.0,0.000,0.088369,-0.996088,0.000,0.000,-0.000,...,0.000000,0.088369,-0.996088,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,-0.0,0.0,0.000,0.088369,-0.996088,0.001,-0.003,-0.001,...,-0.000404,0.089053,-0.996088,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,-0.0,-0.0,0.000,0.088369,-0.996088,0.000,0.000,-0.000,...,0.000000,0.088369,-0.996088,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71987,0.000,0.0,-0.0,0.0,0.000,0.088369,-0.996088,-0.002,-0.001,-0.002,...,-0.004024,0.081263,-0.996088,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [11]:
euler=stop_90[['e_r_x','e_r_y','e_r_z','e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
euler

,e_r_x,e_r_y,e_r_z,e_r_w,d_r_x,d_r_y,d_r_z,d_r_w
0,0.0,0.001,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
1,0.0,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2,0.0,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.001000
3,0.0,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
4,0.0,0.000,0.000000,0.000000,0.000000,0.000000,0.000000,-0.001000
...,...,...,...,...,...,...,...,...
71983,-0.0,0.000,0.088369,-0.996088,-0.000000,0.000000,0.088369,-0.996088
71984,-0.0,0.000,0.088369,-0.996088,-0.000000,0.000000,0.088369,-0.996088
71985,0.0,0.000,0.088369,-0.996088,0.000654,-0.000404,0.089053,-0.996088
71986,-0.0,0.000,0.088369,-0.996088,-0.000000,0.000000,0.088369,-0.996088
71987,0.0,0.000,0.088369,-0.996088,0.006343,-0.004024,0.081263,-0.996088

In [12]:
stop_90_diff = stop_90_without_speed.diff()
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.001,0.0,0.0,0.0,-0.001,0.0,0.0,0.001,0.000,0.000,...,0.000000,0.000000e+00,0.000,0.000,0.000,0.000,-0.001,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.001,0.000,...,0.000000,0.000000e+00,-0.001,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,-0.001,0.000,...,0.000000,0.000000e+00,0.001,0.000,0.000,-0.001,0.001,0.000,-0.001,0.0
4,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,-0.001,...,0.000000,0.000000e+00,-0.001,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,-0.001,0.000,...,0.000005,1.450492e-10,0.000,0.005,0.000,0.000,-0.001,0.001,-0.002,0.0
71984,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.000,0.000,0.000,...,0.000000,0.000000e+00,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.001,-0.003,-0.001,...,-0.000404,6.846015e-04,0.000,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,0.0,-0.0,0.000,0.0,0.0,-0.001,0.003,0.001,...,0.000404,-6.846015e-04,0.000,0.000,0.000,0.000,0.000,0.002,-0.001,0.0
71987,0.000,0.0,0.0,0.0,0.000,0.0,0.0,-0.002,-0.001,-0.002,...,-0.004024,-7.106107e-03,0.000,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [13]:
stop_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.0,0.001,0.000000,0.000000,NaN,NaN,NaN,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.001,0.0,0.0,0.0,0.000,0.000000,0.000000,0.001,0.000,0.000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.001,0.000,...,0.000000,0.000000,-0.001000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,-0.001,0.000,...,0.000000,0.000000,0.000000,0.000,0.000,-0.001,0.001,0.000,-0.001,0.0
4,0.000,0.0,0.0,0.0,0.000,0.000000,0.000000,0.000,0.000,-0.001,...,0.000000,0.000000,-0.001000,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,0.0,-0.0,0.000,0.088369,-0.996088,0.000,-0.001,0.000,...,0.000000,0.088369,-0.996088,0.005,0.000,0.000,-0.001,0.001,-0.002,0.0
71984,0.000,0.0,0.0,-0.0,0.000,0.088369,-0.996088,0.000,0.000,0.000,...,0.000000,0.088369,-0.996088,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,0.0,0.0,0.000,0.088369,-0.996088,0.001,-0.003,-0.001,...,-0.000404,0.089053,-0.996088,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,0.0,-0.0,0.000,0.088369,-0.996088,-0.001,0.003,0.001,...,0.000000,0.088369,-0.996088,0.000,0.000,0.000,0.000,0.002,-0.001,0.0
71987,0.000,0.0,0.0,0.0,0.000,0.088369,-0.996088,-0.002,-0.001,-0.002,...,-0.004024,0.081263,-0.996088,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [14]:
forward_90 = pd.read_csv('data/0_90_quat.csv', sep=",")
forward_90_without_speed = forward_90[forward_90.columns[:-1]]
euler_forward_90=forward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
forward_90_diff = forward_90_without_speed.diff()
forward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_forward_90
forward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.000,0.000,0.000,0.000,NaN,NaN,NaN,...,0.000,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,0.000,0.000,0.000,...,-0.001,0.000,0.000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.000,0.000,-0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,0.001,0.000,0.001,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,-0.003,-0.001,0.003,0.000,0.006,-0.005,0.005,0.000,0.000,0.000,...,0.001,-0.001,-0.001,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,0.002,0.003,0.016,0.000,0.000,0.000,0.000,0.000,0.000,0.000,...,0.000,0.000,0.000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,0.001,0.000,-0.006,-0.002,-0.012,0.011,0.001,0.000,0.000,-0.003,...,-0.024,0.016,-0.020,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,-0.001,0.000,0.006,0.000,0.000,0.000,0.000,0.000,0.000,0.003,...,0.000,0.000,0.000,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,0.007,0.004,0.037,...,-0.017,0.012,-0.022,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [15]:
left_90 = pd.read_csv('data/90_90_quat.csv', sep=",")
left_90_without_speed =left_90[left_90.columns[:-1]]
euler_left_90=left_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
left_90_diff =left_90_without_speed.diff()
left_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_left_90
left_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_z,d_t_y,d_t_x,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.000000,0.000000,0.850904,0.525322,NaN,NaN,NaN,...,0.000000,0.850904,0.525322,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.000176,0.000042,0.850873,0.525371,0.000,0.000,0.000,...,0.000000,0.850904,0.525371,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.000000,0.000000,0.850904,0.525322,0.000,0.000,0.000,...,0.000000,0.850904,0.525322,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.001,0.000,0.000,0.000000,0.000000,0.850904,0.525322,0.000,0.000,0.000,...,0.000000,0.850904,0.525322,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,-0.001,0.000,0.000,0.000000,0.000000,0.850904,0.525322,0.000,0.000,0.000,...,0.000000,0.850904,0.525322,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,-0.003,-0.001,-0.003,-0.002366,-0.000556,0.850149,0.526536,0.000,0.000,0.000,...,-0.000060,0.850904,0.526536,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,-0.016,0.003,0.002,0.000000,0.000000,0.850904,0.525322,0.000,0.000,0.000,...,0.000000,0.850904,0.525322,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,0.006,0.000,0.001,-0.004509,-0.006243,0.851933,0.523594,0.003,0.000,0.000,...,-0.010718,0.837173,0.523594,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,-0.006,0.000,-0.001,0.000000,0.000000,0.850904,0.525322,-0.003,0.000,0.000,...,0.000000,0.850904,0.525322,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,-0.000125,-0.000529,0.850994,0.525176,-0.037,0.004,0.007,...,0.005903,0.844264,0.525176,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [16]:
backward_90 = pd.read_csv('data/180_90_euler.csv', sep=",")
backward_90_without_speed = backward_90[backward_90.columns[:-1]]
euler_backward_90=backward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
backward_90_diff = backward_90_without_speed.diff()
backward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_backward_90
backward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.000,0.000,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,-0.000115,...,0.000000,-0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000115,-0.000344,0.000115,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.000,0.000,0.001,0.000,0.000,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,-0.001,0.000,0.001,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,0.003,-0.001,-0.003,0.000,0.006,-0.005,0.005,-0.005271,0.003552,-0.004699,...,0.000688,0.000000,0.000344,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,-0.002,0.003,-0.016,0.000,0.000,0.000,0.000,0.003438,-0.003438,0.002865,...,0.000000,0.000229,0.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,-0.001,0.000,0.006,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,0.004013,...,-0.055529,0.045837,-0.050504,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,0.001,0.000,-0.006,0.000,0.000,0.000,0.000,0.015360,-0.001146,-0.004013,...,0.055529,-0.045837,0.050504,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,0.000344,...,-0.015823,0.046983,-0.024429,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [17]:
right_90 = pd.read_csv('data/270_90_euler.csv', sep=",")
right_90_without_speed = right_90[right_90.columns[:-1]]
euler_right_90=right_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
right_90_diff = right_90_without_speed.diff()
right_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_right_90
right_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.000,0.000,0.000,0.000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,-0.000115,...,0.000000,-0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.000,0.000,0.000,0.000,0.000115,-0.000344,0.000115,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,-0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.001,0.000,0.000,0.000,0.001,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,0.003,-0.001,0.003,0.000,0.006,-0.005,0.005,-0.005271,0.003552,-0.004699,...,0.000688,0.000000,0.000344,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,0.016,0.003,-0.002,0.000,0.000,0.000,0.000,0.003438,-0.003438,0.002865,...,0.000000,0.000229,0.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,-0.006,0.000,-0.001,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,0.004013,...,-0.055529,0.045837,-0.050504,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,0.006,0.000,0.001,0.000,0.000,0.000,0.000,0.015360,-0.001146,-0.004013,...,0.055529,-0.045837,0.050504,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,0.000344,...,-0.015823,0.046983,-0.024429,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [19]:
stop_90_diff.to_csv('stop_90_diff_quat.csv', index=False, header=True)
forward_90_diff.to_csv('0_90_diff_quat.csv', index=False, header=True)
left_90_diff.to_csv('90_90_diff_quat.csv', index=False, header=True)
backward_90_diff.to_csv('180_90_diff_quat.csv', index=False, header=True)
right_90_diff.to_csv('270_90_diff_quat.csv', index=False, header=True)

In [20]:
for i in stop_90_diff:
    print(i)

e_t_x
e_t_y
e_t_z
e_r_x
e_r_y
e_r_z
e_r_w
d_t_x
d_t_y
d_t_z
d_r_x
d_r_y
d_r_z
d_r_w
c_t_x
c_t_y
c_t_z
c_r_x
c_r_y
c_r_z
c_r_w