In [16]:
from pathlib import Path
import numpy as np
import pandas as pd

In [17]:
stop_45 = pd.read_csv('data/stop_45_quat.csv', sep=",")
stop_45_without_speed = stop_45
euler=stop_45[['e_r_x','e_r_y','e_r_z','e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
stop_45_diff = stop_45_without_speed.diff()
stop_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler
stop_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.127,0.587,0.770,0.215,NaN,NaN,NaN,...,-0.570,-0.806,0.157,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.001,0.000,-0.001,-0.127,0.588,0.770,0.215,0.000,0.000,0.000,...,-0.569,-0.806,0.159,0.013,0.022,-0.004,-0.013,0.010,-0.012,0.002
2,0.001,0.000,0.000,-0.126,0.588,0.769,0.215,0.000,0.000,0.000,...,-0.569,-0.806,0.161,0.010,0.020,-0.005,-0.013,-0.001,-0.011,0.004
3,0.000,0.001,0.000,-0.126,0.590,0.768,0.215,0.000,0.001,0.000,...,-0.570,-0.805,0.162,0.004,0.012,-0.004,-0.007,0.005,-0.015,0.000
4,-0.001,0.000,0.000,-0.127,0.591,0.768,0.213,-0.001,0.000,0.000,...,-0.570,-0.805,0.164,-0.001,0.015,-0.008,-0.006,-0.001,-0.004,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,0.000,0.000,0.000,-0.693,0.021,0.130,0.709,0.074,-0.002,-0.081,...,0.246,0.231,0.572,0.000,0.001,0.002,0.002,0.004,0.000,0.012
3596,0.002,0.000,0.000,-0.693,0.024,0.126,0.710,0.034,-0.014,-0.027,...,0.202,0.172,0.543,-0.002,0.000,0.003,0.003,0.006,0.005,0.016
3597,0.006,0.000,-0.001,-0.694,0.009,0.120,0.710,0.004,-0.002,0.001,...,0.190,0.175,0.574,-0.006,0.001,0.003,-0.001,0.006,-0.003,0.022
3598,0.013,0.001,-0.001,-0.696,-0.009,0.094,0.712,-0.002,0.000,0.001,...,0.187,0.177,0.571,-0.006,0.000,0.001,-0.016,0.004,-0.001,0.019
3599,0.050,0.006,0.008,-0.675,-0.080,0.019,0.733,0.000,-0.001,0.000,...,0.188,0.175,0.571,-0.005,-0.002,0.001,-0.004,0.004,-0.002,0.019

In [18]:
forward_45 = pd.read_csv('data/0_45_quat.csv', sep=",")
forward_45_without_speed = forward_45[forward_45.columns[:-1]]
euler_forward_45=forward_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
forward_45_diff = forward_45_without_speed.diff()
forward_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_forward_45
forward_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.726,0.099,0.334,0.592,NaN,NaN,NaN,-0.777,0.330,0.249,0.475,NaN,NaN,NaN,NaN,NaN,NaN
1,0.012,0.003,-0.009,-0.768,0.005,0.178,0.615,0.001,-0.001,0.000,-0.777,0.332,0.248,0.474,0.012,-0.006,-0.019,0.000,-0.001,-0.009
2,0.003,0.001,0.001,-0.766,0.020,0.173,0.619,0.000,0.001,0.000,-0.778,0.333,0.247,0.472,0.019,-0.004,-0.022,0.002,-0.002,-0.001
3,0.000,0.001,0.000,-0.765,0.015,0.173,0.620,0.000,0.001,-0.001,-0.778,0.334,0.248,0.471,0.019,0.001,-0.028,0.004,-0.002,-0.003
4,0.001,-0.001,0.000,-0.762,0.014,0.174,0.623,-0.002,0.001,-0.001,-0.782,0.334,0.261,0.457,0.012,-0.013,-0.021,0.009,-0.002,-0.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3595,-0.002,0.023,0.088,0.004,0.712,0.680,0.175,0.000,0.001,0.000,-0.039,-0.634,-0.769,0.077,-0.001,0.004,0.003,0.004,0.004,0.006
3596,0.044,-0.007,0.012,0.040,0.714,0.691,0.102,0.000,0.000,0.001,-0.037,-0.633,-0.770,0.079,-0.010,0.001,0.004,0.001,-0.002,-0.005
3597,0.006,-0.016,-0.080,-0.048,0.679,0.710,0.180,0.000,0.000,0.000,-0.039,-0.632,-0.770,0.078,-0.021,0.001,0.001,-0.004,0.010,0.002
3598,0.004,-0.011,-0.065,-0.086,0.674,0.703,0.210,0.000,0.001,-0.001,-0.043,-0.641,-0.763,0.069,-0.029,-0.002,-0.003,-0.013,0.003,0.002
3599,-0.005,-0.001,0.006,-0.089,0.657,0.721,0.203,-0.003,0.000,0.002,-0.027,-0.629,-0.773,0.073,-0.025,-0.002,-0.003,-0.009,0.011,0.008

In [19]:
d_f_e_45 = pd.read_csv('data/45_45_quat.csv', sep=",")
d_f_e_45_without_speed = d_f_e_45[d_f_e_45.columns[:-1]]
euler_d_f_e_45=d_f_e_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
d_f_e_45_diff = d_f_e_45_without_speed.diff()
d_f_e_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_d_f_e_45
d_f_e_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,0.009,0.521,0.845,0.121,NaN,NaN,NaN,-0.089,-0.549,-0.807,0.200,NaN,NaN,NaN,NaN,NaN,NaN
1,0.006,0.024,0.077,-0.016,0.407,0.900,0.157,0.002,-0.001,0.000,-0.093,-0.549,-0.808,0.194,0.015,0.001,-0.013,0.011,0.004,-0.010
2,-0.004,0.015,0.134,-0.034,0.575,0.802,0.157,0.002,0.002,0.000,-0.093,-0.548,-0.808,0.194,0.000,0.008,-0.003,-0.004,0.002,0.006
3,-0.037,0.026,0.121,-0.071,0.669,0.713,0.198,0.000,0.000,0.000,-0.092,-0.549,-0.807,0.197,-0.008,0.000,0.009,-0.014,0.001,0.001
4,0.005,-0.007,0.005,-0.040,0.655,0.743,0.131,0.000,-0.001,0.001,-0.091,-0.545,-0.809,0.200,-0.021,-0.002,0.020,0.000,0.007,-0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.001,0.000,0.001,-0.357,0.520,0.625,0.460,0.009,0.013,-0.008,-0.168,0.600,0.780,0.058,0.016,0.000,0.020,-0.002,-0.004,-0.003
2396,0.000,0.003,0.000,-0.361,0.524,0.623,0.456,0.000,0.003,-0.002,-0.161,0.623,0.762,0.080,0.020,0.005,0.019,0.004,0.003,-0.005
2397,0.000,0.000,0.000,-0.359,0.522,0.624,0.457,0.000,-0.001,0.000,-0.159,0.626,0.759,0.082,0.021,0.001,0.010,-0.004,0.011,-0.009
2398,-0.001,0.000,0.000,-0.359,0.523,0.624,0.456,0.000,0.000,0.000,-0.159,0.626,0.759,0.082,0.018,0.002,0.005,-0.001,0.012,-0.012
2399,0.000,0.000,0.000,-0.359,0.522,0.625,0.456,0.000,0.000,0.000,-0.159,0.625,0.760,0.081,0.008,0.004,0.001,-0.007,0.006,-0.011

In [20]:
left_45 = pd.read_csv('data/90_45_quat.csv', sep=",")
left_45_without_speed =left_45
euler_left_45=left_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
left_45_diff =left_45_without_speed.diff()
left_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_left_45
left_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.290,0.504,0.748,0.320,NaN,NaN,NaN,...,-0.372,-0.895,0.068,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.001,-0.293,0.502,0.749,0.318,-0.056,0.025,0.097,...,-0.496,-0.835,0.056,-0.003,0.002,-0.015,0.004,0.007,0.006,0.003
2,0.000,0.000,0.000,-0.292,0.502,0.749,0.318,-0.066,0.020,0.121,...,-0.619,-0.746,0.020,0.004,0.010,-0.002,-0.017,0.010,-0.004,0.004
3,0.000,0.000,-0.001,-0.291,0.502,0.750,0.319,-0.039,0.023,0.079,...,0.691,0.685,0.006,0.003,0.001,0.012,-0.012,-0.006,0.001,-0.003
4,0.000,0.000,0.001,-0.290,0.498,0.751,0.321,-0.020,-0.009,-0.010,...,0.665,0.687,0.075,0.005,-0.002,0.030,0.001,-0.006,-0.001,-0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.002,0.004,0.001,-0.538,0.353,0.461,0.611,-0.011,0.000,0.002,...,0.487,0.649,0.303,0.007,-0.003,-0.015,0.001,0.012,0.010,0.009
2396,0.006,-0.006,0.002,-0.542,0.355,0.459,0.608,-0.082,0.037,-0.010,...,0.411,0.650,0.293,0.011,0.003,-0.009,-0.002,0.004,0.009,0.004
2397,0.001,0.001,-0.004,-0.545,0.353,0.454,0.610,-0.110,0.009,0.032,...,0.488,0.605,0.334,0.007,0.009,-0.001,-0.015,-0.005,-0.005,-0.001
2398,0.000,-0.001,0.000,-0.545,0.349,0.456,0.611,-0.055,0.014,0.012,...,0.541,0.549,0.418,0.002,0.006,0.009,-0.016,-0.007,-0.018,-0.002
2399,0.000,0.001,0.000,-0.546,0.349,0.456,0.610,0.128,-0.036,-0.009,...,0.531,0.599,0.370,0.002,0.003,0.019,-0.003,-0.007,-0.009,-0.004

In [21]:
d_t_e_45 = pd.read_csv('data/135_45_quat.csv', sep=",")
d_t_e_45_without_speed = d_t_e_45[d_t_e_45.columns[:-1]]
euler_d_t_e_45=d_t_e_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
d_t_e_45_diff = d_t_e_45_without_speed.diff()
d_t_e_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_d_t_e_45
d_t_e_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.585,0.306,0.555,0.505,NaN,NaN,NaN,-0.537,0.590,0.495,0.345,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.001,0.001,0.0,-0.585,0.304,0.556,0.505,-0.003,0.004,-0.001,-0.558,0.570,0.490,0.351,-0.011,-0.002,0.018,0.010,0.004,0.002
2,0.000,0.000,0.0,-0.585,0.303,0.557,0.506,0.074,-0.027,0.006,-0.543,0.553,0.550,0.311,-0.006,0.000,0.027,0.011,0.002,-0.013
3,0.000,0.000,0.0,-0.585,0.301,0.559,0.505,0.157,-0.026,-0.019,-0.552,0.525,0.588,0.272,0.004,0.005,0.061,0.010,-0.002,-0.023
4,0.000,0.000,0.0,-0.585,0.300,0.559,0.505,0.094,-0.009,-0.020,-0.551,0.510,0.603,0.268,0.013,0.001,0.038,0.005,-0.002,-0.011
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.000,0.000,0.0,-0.666,0.149,0.298,0.668,-0.125,0.041,-0.092,-0.776,0.282,0.370,0.426,0.003,0.017,-0.008,0.018,0.004,0.031
2396,0.000,0.000,0.0,-0.665,0.148,0.297,0.669,-0.055,0.004,-0.074,-0.711,0.288,0.285,0.575,-0.010,0.004,-0.006,0.009,0.006,0.026
2397,0.000,0.000,0.0,-0.664,0.149,0.297,0.669,0.040,-0.022,0.029,-0.705,0.320,0.253,0.580,-0.016,-0.003,0.002,-0.005,0.001,-0.006
2398,0.000,0.000,0.0,-0.665,0.148,0.298,0.669,0.120,-0.022,0.104,-0.681,0.338,0.372,0.532,-0.025,-0.008,0.016,-0.018,-0.002,-0.034
2399,0.000,0.001,0.0,-0.663,0.152,0.298,0.669,0.049,-0.005,0.052,-0.618,0.385,0.436,0.530,-0.018,-0.004,0.018,-0.001,0.001,-0.003

In [22]:
backward_45 = pd.read_csv('data/180_45_quat.csv', sep=",")
backward_45_without_speed = backward_45
euler_backward_45=backward_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
backward_45_diff = backward_45_without_speed.diff()
backward_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_backward_45
backward_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.817,-0.049,0.355,0.452,NaN,NaN,NaN,...,0.393,0.417,0.400,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.100,0.012,-0.086,-0.758,0.078,0.300,0.574,0.001,-0.001,0.000,...,0.394,0.417,0.399,0.008,0.009,0.004,0.012,0.002,0.000,0.002
2,-0.044,0.024,-0.101,-0.700,0.065,0.245,0.668,0.002,-0.002,0.000,...,0.397,0.417,0.399,0.007,0.003,-0.011,0.013,0.001,0.015,0.002
3,-0.006,-0.006,-0.013,-0.712,0.094,0.269,0.642,0.001,-0.002,0.000,...,0.398,0.417,0.396,0.007,0.003,-0.023,0.009,0.001,0.013,0.004
4,0.053,-0.014,0.051,-0.729,0.072,0.251,0.633,0.002,-0.001,0.000,...,0.400,0.416,0.391,0.012,0.003,-0.039,0.006,0.005,0.005,0.015
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.001,0.001,0.001,-0.709,-0.203,-0.097,0.668,-0.005,-0.021,0.128,...,0.110,0.080,0.644,-0.024,0.003,-0.002,-0.009,0.000,0.000,0.006
2396,0.000,0.001,0.000,-0.706,-0.202,-0.097,0.672,0.004,-0.016,0.096,...,0.137,0.117,0.628,-0.027,0.001,0.005,-0.009,0.000,-0.001,-0.001
2397,-0.001,0.004,0.002,-0.698,-0.209,-0.092,0.679,-0.009,0.002,0.015,...,0.140,0.161,0.592,-0.032,0.004,0.009,-0.004,0.000,-0.004,-0.007
2398,-0.001,0.003,-0.044,-0.722,-0.195,-0.069,0.660,0.002,-0.006,-0.001,...,0.150,0.145,0.609,-0.019,-0.007,0.010,-0.014,-0.001,-0.011,-0.006
2399,0.004,0.022,-0.095,-0.676,-0.166,-0.054,0.716,0.001,0.000,-0.002,...,0.149,0.144,0.610,-0.005,0.009,-0.003,0.000,0.000,0.018,-0.005

In [23]:
d_t_d_45 = pd.read_csv('data/225_45_quat.csv', sep=",")
d_t_d_45_without_speed = d_t_d_45[d_t_d_45.columns[:-1]]
euler_d_t_d_45=d_t_d_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
d_t_d_45_diff = d_t_d_45_without_speed.diff()
d_t_d_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_d_t_d_45
d_t_d_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.862,-0.133,0.000,0.489,NaN,NaN,NaN,-0.821,0.192,0.068,0.534,NaN,NaN,NaN,NaN,NaN,NaN
1,0.019,0.024,-0.156,-0.758,-0.138,-0.027,0.637,-0.001,0.000,0.000,-0.820,0.193,0.068,0.535,0.004,0.005,-0.004,0.008,0.001,0.020
2,0.016,0.011,-0.061,-0.729,-0.151,0.010,0.668,0.001,-0.001,0.000,-0.819,0.195,0.067,0.535,0.018,-0.001,-0.017,-0.005,0.000,0.013
3,0.008,-0.019,0.057,-0.776,-0.127,0.004,0.618,0.000,0.001,-0.001,-0.820,0.197,0.067,0.533,0.032,0.000,-0.021,0.014,0.000,-0.007
4,-0.007,-0.023,0.109,-0.794,-0.126,0.014,0.594,0.000,-0.001,-0.001,-0.822,0.199,0.066,0.530,0.037,-0.005,-0.018,-0.003,0.000,-0.021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.058,-0.024,0.090,-0.595,-0.480,-0.354,0.539,-0.001,0.000,0.000,-0.757,-0.116,-0.181,0.617,0.000,0.000,0.000,0.000,0.000,0.000
2396,-0.064,-0.015,0.050,-0.600,-0.458,-0.364,0.546,0.000,-0.002,-0.001,-0.755,-0.112,-0.183,0.619,0.000,0.000,0.000,0.000,0.000,0.000
2397,0.007,-0.002,-0.006,-0.599,-0.478,-0.352,0.538,0.001,0.002,-0.002,-0.780,-0.095,-0.185,0.590,0.000,0.000,0.000,0.000,0.000,0.000
2398,0.001,0.002,0.000,-0.607,-0.456,-0.371,0.535,0.030,0.004,-0.024,-0.905,0.058,-0.255,0.336,0.000,0.000,0.000,0.000,0.000,0.000
2399,0.000,0.000,-0.001,-0.608,-0.454,-0.373,0.534,0.100,0.034,-0.090,-0.808,-0.120,-0.255,0.517,0.000,0.000,0.000,0.000,0.000,0.000

In [24]:
right_45 = pd.read_csv('data/270_45_quat.csv', sep=",")
right_45_without_speed = right_45
euler_right_45=right_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
right_45_diff = right_45_without_speed.diff()
right_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_right_45
right_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.730,-0.358,-0.333,0.479,NaN,NaN,NaN,...,0.009,-0.193,0.563,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.006,-0.003,-0.004,-0.731,-0.360,-0.324,0.481,0.003,0.002,-0.005,...,0.020,-0.201,0.514,0.022,-0.001,0.033,0.018,-0.004,0.002,0.006
2,0.001,-0.001,-0.002,-0.739,-0.353,-0.330,0.470,0.016,0.012,-0.049,...,0.063,-0.262,0.386,0.008,0.003,0.022,0.010,0.000,-0.005,0.000
3,0.000,0.000,0.000,-0.739,-0.353,-0.330,0.470,0.014,0.020,-0.136,...,0.087,-0.214,0.566,-0.003,0.008,0.009,-0.006,0.003,0.011,-0.005
4,0.000,-0.001,0.000,-0.739,-0.357,-0.327,0.469,-0.016,0.035,-0.140,...,0.136,-0.119,0.669,-0.008,0.002,-0.007,-0.007,-0.001,0.011,0.002
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.116,-0.020,-0.033,-0.411,-0.636,-0.574,0.311,0.001,0.000,0.000,...,-0.379,-0.489,0.512,0.003,-0.009,0.027,0.025,0.027,-0.003,-0.030
2396,0.005,0.005,0.005,-0.428,-0.648,-0.555,0.298,-0.003,0.000,0.009,...,-0.377,-0.566,0.464,-0.014,-0.014,0.036,0.022,0.027,0.012,-0.033
2397,0.003,-0.001,0.002,-0.433,-0.624,-0.580,0.296,0.033,0.056,-0.039,...,-0.272,-0.635,0.406,-0.010,0.008,0.010,-0.011,0.008,0.017,-0.007
2398,0.002,0.000,-0.001,-0.435,-0.621,-0.581,0.295,0.051,0.036,-0.054,...,-0.162,-0.567,0.472,-0.004,0.017,0.002,-0.004,-0.001,-0.001,0.001
2399,-0.004,-0.002,-0.003,-0.434,-0.623,-0.580,0.296,0.074,-0.018,0.019,...,-0.273,-0.558,0.450,0.000,0.006,-0.012,-0.011,0.002,-0.005,-0.001

In [25]:
d_f_d_45 = pd.read_csv('data/315_45_quat.csv', sep=",")
d_f_d_45_without_speed = d_f_d_45[d_f_d_45.columns[:-1]]
euler_d_f_d_45=d_f_d_45[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
d_f_d_45_diff = d_f_d_45_without_speed.diff()
d_f_d_45_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_d_f_d_45
d_f_d_45_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.558,-0.501,-0.606,0.267,NaN,NaN,NaN,-0.655,-0.223,-0.496,0.525,NaN,NaN,NaN,NaN,NaN,NaN
1,0.015,0.003,0.005,-0.549,-0.455,-0.678,0.180,0.001,0.000,0.001,-0.654,-0.222,-0.494,0.527,-0.013,-0.004,-0.025,-0.002,0.000,-0.014
2,0.097,0.012,-0.014,-0.541,-0.501,-0.639,0.218,0.001,0.000,0.000,-0.655,-0.220,-0.496,0.526,-0.008,0.005,-0.010,0.001,0.001,-0.013
3,0.139,0.018,0.001,-0.515,-0.544,-0.570,0.338,0.000,0.000,0.000,-0.654,-0.220,-0.496,0.528,0.001,0.006,0.004,-0.016,0.002,0.009
4,0.091,0.022,0.022,-0.508,-0.581,-0.534,0.344,0.001,-0.001,0.001,-0.653,-0.217,-0.497,0.529,0.014,0.000,0.019,-0.004,-0.003,0.005
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.028,0.008,0.026,-0.304,-0.640,-0.701,0.080,-0.001,0.000,0.001,-0.480,-0.485,-0.616,0.394,0.004,-0.001,-0.009,0.007,-0.001,-0.006
2396,0.055,0.018,0.055,-0.302,-0.696,-0.643,0.107,0.001,0.000,-0.001,-0.481,-0.484,-0.616,0.394,0.003,0.006,0.004,-0.003,-0.006,0.008
2397,0.052,0.009,0.024,-0.286,-0.718,-0.613,0.167,0.000,0.000,0.001,-0.481,-0.484,-0.616,0.394,0.002,0.000,0.014,-0.006,-0.006,0.001
2398,-0.049,-0.016,-0.025,-0.213,-0.701,-0.670,0.118,0.000,0.001,0.000,-0.482,-0.484,-0.616,0.393,-0.007,-0.001,0.018,0.003,0.006,0.005
2399,-0.055,-0.017,-0.074,-0.241,-0.695,-0.671,0.096,0.001,0.000,0.001,-0.482,-0.482,-0.617,0.394,-0.019,0.004,0.019,-0.016,0.013,0.011

In [26]:
# stop = stop_passado.append(stop_90_diff, ignore_index=True)
# forward = frente_passado.append(forward_90_diff, ignore_index=True)
# left = esquerda_passado.append(left_90_diff, ignore_index=True)
# backward = tras_passado.append(backward_90_diff, ignore_index=True)
# right = direita_passado.append(right_90_diff, ignore_index=True)

In [27]:
# stop_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
# frente_passado = pd.read_csv('data/0_90_diff_quat.csv', sep=",")
# esquerda_passado = pd.read_csv('data/90_90_diff_quat.csv', sep=",")
# tras_passado = pd.read_csv('data/180_90_diff_quat.csv', sep=",")
# direita_passado = pd.read_csv('data/270_90_diff_quat.csv', sep=",")

In [28]:
# stop = stop_passado.append(stop_90_diff, ignore_index=True)
# forward = frente_passado.append(forward_90_diff, ignore_index=True)
# left = esquerda_passado.append(left_90_diff, ignore_index=True)
# backward = tras_passado.append(backward_90_diff, ignore_index=True)
# right = direita_passado.append(right_90_diff, ignore_index=True)

In [29]:
# stop.to_csv('stop_90_diff_quat.csv', index=False, header=True)
# forward.to_csv('0_90_diff_quat.csv', index=False, header=True)
# left.to_csv('90_90_diff_quat.csv', index=False, header=True)
# backward.to_csv('180_90_diff_quat.csv', index=False, header=True)
# right.to_csv('270_90_diff_quat.csv', index=False, header=True)

In [30]:
stop_45_diff.to_csv('data/stop_45_diff_quat.csv', index=False, header=True)
forward_45_diff.to_csv('data/0_45_diff_quat.csv', index=False, header=True)
d_f_e_45_diff.to_csv('data/45_45_diff_quat.csv', index=False, header=True)
left_45_diff.to_csv('data/90_45_diff_quat.csv', index=False, header=True)
d_t_e_45_diff.to_csv('data/135_45_diff_quat.csv', index=False, header=True)
backward_45_diff.to_csv('data/180_45_diff_quat.csv', index=False, header=True)
d_t_d_45_diff.to_csv('data/225_45_diff_quat.csv', index=False, header=True)
right_45_diff.to_csv('data/270_45_diff_quat.csv', index=False, header=True)
d_f_d_45_diff.to_csv('data/315_45_diff_quat.csv', index=False, header=True)