In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

In [2]:
stop_90 = pd.read_csv('data/stop_90_quat.csv', sep=",")
stop_90_without_speed = stop_90
stop_90_without_speed

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,-0.117,0.619,0.199,-0.029,-0.700,-0.704,0.117,0.119,0.622,0.164,...,-0.702,-0.673,0.120,-0.048,2.149,0.035,-0.092,-0.687,0.129,0.709
1,-0.117,0.619,0.198,-0.029,-0.700,-0.704,0.117,0.118,0.622,0.164,...,-0.703,-0.672,0.120,-0.042,2.151,0.037,-0.096,-0.679,0.124,0.718
2,-0.117,0.619,0.198,-0.030,-0.700,-0.704,0.116,0.119,0.622,0.164,...,-0.703,-0.672,0.119,-0.039,2.153,0.038,-0.099,-0.670,0.119,0.726
3,-0.117,0.619,0.198,-0.030,-0.700,-0.704,0.116,0.119,0.622,0.164,...,-0.703,-0.672,0.119,-0.037,2.153,0.039,-0.099,-0.661,0.119,0.734
4,-0.117,0.619,0.198,-0.030,-0.700,-0.704,0.116,0.118,0.622,0.164,...,-0.703,-0.672,0.119,-0.035,2.153,0.039,-0.100,-0.655,0.118,0.740
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.049,0.616,-0.114,-0.634,0.404,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.410,-0.072,2.132,-0.012,0.012,0.926,-0.045,-0.375
2396,-0.048,0.616,-0.114,-0.633,0.405,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.069,2.133,-0.014,0.016,0.931,-0.047,-0.363
2397,-0.048,0.616,-0.114,-0.632,0.407,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.064,2.133,-0.018,0.018,0.944,-0.049,-0.324
2398,-0.048,0.616,-0.115,-0.632,0.408,0.345,0.562,-0.108,0.623,0.224,...,0.574,0.593,0.411,-0.055,2.133,-0.024,0.030,0.961,-0.052,-0.271
2399,-0.048,0.616,-0.115,-0.632,0.408,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.045,2.133,-0.030,0.039,0.975,-0.048,-0.212

In [3]:
euler=stop_90[['e_r_x','e_r_y','e_r_z','e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
euler

      e_r_x  e_r_y  e_r_z  e_r_w  d_r_x  d_r_y  d_r_z  d_r_w
0    -0.029 -0.700 -0.704  0.117 -0.200 -0.702 -0.673  0.120
1    -0.029 -0.700 -0.704  0.117 -0.200 -0.703 -0.672  0.120
2    -0.030 -0.700 -0.704  0.116 -0.200 -0.703 -0.672  0.119
3    -0.030 -0.700 -0.704  0.116 -0.200 -0.703 -0.672  0.119
4    -0.030 -0.700 -0.704  0.116 -0.200 -0.703 -0.672  0.119
...     ...    ...    ...    ...    ...    ...    ...    ...
2395 -0.634  0.404  0.345  0.562 -0.387  0.575  0.593  0.410
2396 -0.633  0.405  0.345  0.562 -0.387  0.575  0.593  0.411
2397 -0.632  0.407  0.345  0.562 -0.387  0.575  0.593  0.411
2398 -0.632  0.408  0.345  0.562 -0.387  0.574  0.593  0.411
2399 -0.632  0.408  0.345  0.562 -0.387  0.575  0.593  0.411

[2400 rows x 8 columns]

In [4]:
stop_90_diff = stop_90_without_speed.diff()
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.0,-0.001,0.000,0.000,0.0,0.000,-0.001,0.0,0.0,...,-0.001,0.001,0.000,0.006,0.002,0.002,-0.004,0.008,-0.005,0.009
2,0.000,0.0,0.000,-0.001,0.000,0.0,-0.001,0.001,0.0,0.0,...,0.000,0.000,-0.001,0.003,0.002,0.001,-0.003,0.009,-0.005,0.008
3,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.0,...,0.000,0.000,0.000,0.002,0.000,0.001,0.000,0.009,0.000,0.008
4,0.000,0.0,0.000,0.000,0.000,0.0,0.000,-0.001,0.0,0.0,...,0.000,0.000,0.000,0.002,0.000,0.000,-0.001,0.006,-0.001,0.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.000,0.0,0.000,0.000,0.001,0.0,0.000,0.001,0.0,0.0,...,0.000,0.000,0.000,0.002,0.000,-0.001,0.002,0.004,0.000,0.009
2396,0.001,0.0,0.000,0.001,0.001,0.0,0.000,0.000,0.0,0.0,...,0.000,0.000,0.001,0.003,0.001,-0.002,0.004,0.005,-0.002,0.012
2397,0.000,0.0,0.000,0.001,0.002,0.0,0.000,0.000,0.0,0.0,...,0.000,0.000,0.000,0.005,0.000,-0.004,0.002,0.013,-0.002,0.039
2398,0.000,0.0,-0.001,0.000,0.001,0.0,0.000,0.000,0.0,0.0,...,-0.001,0.000,0.000,0.009,0.000,-0.006,0.012,0.017,-0.003,0.053
2399,0.000,0.0,0.000,0.000,0.000,0.0,0.000,0.000,0.0,0.0,...,0.001,0.000,0.000,0.010,0.000,-0.006,0.009,0.014,0.004,0.059

In [5]:
stop_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.029,-0.700,-0.704,0.117,NaN,NaN,NaN,...,-0.702,-0.673,0.120,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.0,-0.001,-0.029,-0.700,-0.704,0.117,-0.001,0.0,0.0,...,-0.703,-0.672,0.120,0.006,0.002,0.002,-0.004,0.008,-0.005,0.009
2,0.000,0.0,0.000,-0.030,-0.700,-0.704,0.116,0.001,0.0,0.0,...,-0.703,-0.672,0.119,0.003,0.002,0.001,-0.003,0.009,-0.005,0.008
3,0.000,0.0,0.000,-0.030,-0.700,-0.704,0.116,0.000,0.0,0.0,...,-0.703,-0.672,0.119,0.002,0.000,0.001,0.000,0.009,0.000,0.008
4,0.000,0.0,0.000,-0.030,-0.700,-0.704,0.116,-0.001,0.0,0.0,...,-0.703,-0.672,0.119,0.002,0.000,0.000,-0.001,0.006,-0.001,0.006
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.000,0.0,0.000,-0.634,0.404,0.345,0.562,0.001,0.0,0.0,...,0.575,0.593,0.410,0.002,0.000,-0.001,0.002,0.004,0.000,0.009
2396,0.001,0.0,0.000,-0.633,0.405,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.003,0.001,-0.002,0.004,0.005,-0.002,0.012
2397,0.000,0.0,0.000,-0.632,0.407,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.005,0.000,-0.004,0.002,0.013,-0.002,0.039
2398,0.000,0.0,-0.001,-0.632,0.408,0.345,0.562,0.000,0.0,0.0,...,0.574,0.593,0.411,0.009,0.000,-0.006,0.012,0.017,-0.003,0.053
2399,0.000,0.0,0.000,-0.632,0.408,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.010,0.000,-0.006,0.009,0.014,0.004,0.059

In [6]:
forward_90 = pd.read_csv('data/0_90_quat.csv', sep=",")
forward_90_without_speed = forward_90[forward_90.columns[:-1]]
euler_forward_90=forward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
forward_90_diff = forward_90_without_speed.diff()
forward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_forward_90
forward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.632,0.408,0.345,0.562,NaN,NaN,NaN,-0.387,0.574,0.593,0.411,NaN,NaN,NaN,NaN,NaN,NaN
1,0.0,0.000,0.000,-0.632,0.409,0.344,0.562,0.000,0.000,0.000,-0.387,0.574,0.593,0.411,0.008,0.000,-0.004,0.008,0.005,-0.002
2,0.0,0.000,0.000,-0.632,0.409,0.344,0.562,0.000,0.000,0.000,-0.387,0.575,0.593,0.410,0.005,-0.001,-0.002,0.007,0.002,-0.001
3,0.0,0.000,0.000,-0.632,0.409,0.344,0.562,0.000,0.000,0.000,-0.387,0.575,0.593,0.410,0.003,-0.001,-0.002,0.004,0.000,-0.005
4,0.0,0.000,0.000,-0.632,0.409,0.344,0.561,0.000,-0.001,0.000,-0.388,0.575,0.593,0.410,0.002,0.000,-0.002,0.001,0.000,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.0,0.000,0.000,0.016,-0.703,-0.709,0.048,-0.001,0.007,0.041,0.105,0.728,0.676,0.035,0.022,-0.001,0.009,0.008,-0.009,0.009
2396,0.0,0.000,0.000,0.015,-0.703,-0.709,0.048,0.000,-0.013,-0.058,0.064,0.730,0.678,0.051,0.039,-0.001,0.004,0.016,-0.004,-0.007
2397,0.0,0.000,0.000,0.014,-0.703,-0.709,0.049,0.020,-0.017,-0.097,0.068,0.714,0.696,0.015,0.041,0.002,0.001,-0.010,-0.003,-0.013
2398,0.0,0.001,0.000,0.014,-0.704,-0.709,0.049,0.012,-0.009,-0.085,-0.070,-0.706,-0.704,0.002,0.040,0.001,0.002,-0.007,-0.001,-0.014
2399,0.0,0.000,-0.001,0.014,-0.704,-0.708,0.049,0.004,-0.006,-0.063,-0.085,-0.707,-0.702,0.001,0.048,0.000,0.002,-0.003,0.002,-0.014

In [7]:
left_90 = pd.read_csv('data/90_90_quat.csv', sep=",")
left_90_without_speed =left_90
euler_left_90=left_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
left_90_diff =left_90_without_speed.diff()
left_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_left_90
left_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.016,-0.703,-0.709,0.050,NaN,NaN,NaN,...,-0.692,-0.715,0.018,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.001,0.000,0.000,0.017,-0.699,-0.714,0.047,0.000,-0.002,0.001,...,-0.706,-0.701,0.019,0.040,-0.004,-0.008,0.014,-0.001,-0.030,-0.001
2,0.002,0.002,0.001,0.012,-0.695,-0.718,0.037,0.000,0.000,0.000,...,-0.710,-0.698,0.018,0.026,-0.004,-0.010,0.007,0.009,-0.034,-0.001
3,0.015,0.003,0.032,-0.044,-0.665,-0.743,0.052,0.000,0.000,0.000,...,-0.710,-0.697,0.017,-0.003,-0.001,-0.003,0.000,-0.022,-0.026,-0.002
4,-0.009,0.022,0.102,-0.039,-0.719,-0.690,0.074,0.000,0.000,0.000,...,-0.709,-0.698,0.016,-0.013,0.006,0.004,-0.013,-0.004,-0.001,-0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.085,0.004,-0.014,-0.501,0.577,0.440,0.471,-0.001,0.000,0.000,...,0.563,0.591,0.433,-0.009,0.000,-0.015,-0.004,0.001,-0.007,0.001
2396,0.000,-0.005,0.012,-0.469,0.584,0.491,0.444,0.000,-0.001,0.000,...,0.563,0.591,0.432,-0.011,-0.002,-0.025,0.005,0.010,0.011,0.010
2397,0.077,-0.012,-0.002,-0.485,0.552,0.509,0.449,0.000,0.001,0.000,...,0.563,0.591,0.433,-0.002,0.000,-0.031,-0.002,0.005,0.034,0.010
2398,0.076,-0.008,-0.006,-0.521,0.531,0.493,0.452,0.001,0.000,0.001,...,0.562,0.591,0.433,0.000,0.001,-0.031,-0.017,0.004,0.027,0.009
2399,0.078,-0.007,0.012,-0.504,0.553,0.512,0.421,0.000,0.000,0.000,...,0.561,0.592,0.435,-0.001,0.000,-0.046,-0.031,0.001,0.041,0.007

In [8]:
backward_90 = pd.read_csv('data/180_90_quat.csv', sep=",")
backward_90_without_speed = backward_90
euler_backward_90=backward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
backward_90_diff = backward_90_without_speed.diff()
backward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_backward_90
backward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.518,0.529,0.497,0.452,NaN,NaN,NaN,...,0.561,0.594,0.435,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.002,0.000,-0.001,-0.521,0.536,0.495,0.444,0.000,0.001,0.000,...,0.560,0.597,0.433,-0.001,-0.002,-0.049,-0.019,-0.015,0.045,-0.015
2,-0.001,-0.002,0.000,-0.517,0.538,0.495,0.446,0.000,0.001,0.001,...,0.557,0.607,0.421,0.005,-0.008,-0.033,-0.027,-0.026,0.015,-0.026
3,-0.002,0.000,0.000,-0.516,0.539,0.494,0.446,-0.014,0.000,0.007,...,0.557,0.627,0.401,0.004,-0.004,-0.006,-0.011,-0.005,0.010,-0.007
4,0.000,0.000,0.000,-0.516,0.538,0.496,0.445,-0.087,0.014,-0.015,...,0.543,0.590,0.437,-0.004,0.003,0.006,-0.010,-0.001,0.001,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,-0.021,0.013,-0.097,-0.713,0.135,0.049,0.686,0.000,0.001,0.000,...,0.098,0.153,0.690,0.001,0.003,0.002,-0.029,0.003,0.019,-0.010
2396,0.001,0.009,-0.083,-0.682,0.126,0.016,0.720,-0.001,-0.001,0.000,...,0.098,0.152,0.690,0.010,0.000,-0.008,-0.013,0.003,0.021,-0.018
2397,0.007,0.001,-0.015,-0.684,0.124,0.007,0.719,0.001,0.000,0.000,...,0.098,0.152,0.689,0.017,0.001,-0.011,-0.014,0.001,0.001,-0.015
2398,0.020,-0.014,0.051,-0.713,0.109,-0.008,0.693,0.000,0.001,0.000,...,0.097,0.152,0.689,0.031,-0.002,-0.009,0.003,-0.001,-0.018,-0.010
2399,0.013,-0.007,0.079,-0.728,0.107,0.024,0.677,-0.001,0.000,0.000,...,0.097,0.152,0.689,0.032,0.002,-0.006,0.018,0.000,-0.005,-0.009

In [9]:
right_90 = pd.read_csv('data/270_90_quat.csv', sep=",")
right_90_without_speed = right_90
euler_right_90=right_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
right_90_diff = right_90_without_speed.diff()
right_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_right_90
right_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.742,0.087,0.017,0.665,NaN,NaN,NaN,...,0.095,0.154,0.689,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,-0.001,0.031,-0.725,0.104,0.034,0.680,-0.001,0.000,0.000,...,0.097,0.158,0.689,0.043,0.004,-0.005,0.017,0.000,0.011,-0.020
2,0.001,-0.001,-0.002,-0.733,0.096,0.023,0.673,-0.002,0.000,0.001,...,0.103,0.165,0.687,0.042,0.003,-0.004,0.016,-0.001,0.005,-0.013
3,-0.001,-0.001,-0.001,-0.731,0.097,0.024,0.675,-0.003,0.002,0.002,...,0.116,0.175,0.684,0.035,-0.006,0.001,0.036,-0.003,-0.010,0.006
4,0.000,0.000,0.001,-0.729,0.098,0.024,0.677,-0.004,0.001,-0.004,...,0.134,0.201,0.664,0.031,-0.015,0.009,0.038,-0.005,-0.013,0.013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2395,0.000,0.000,0.000,-0.526,-0.432,-0.490,0.545,0.092,0.012,-0.007,...,-0.455,-0.404,0.524,-0.003,0.003,-0.007,-0.006,0.001,0.018,-0.001
2396,0.000,0.000,0.000,-0.528,-0.432,-0.489,0.543,0.085,0.006,-0.006,...,-0.499,-0.350,0.531,0.002,-0.004,-0.013,0.013,-0.009,0.005,0.005
2397,-0.001,-0.001,0.000,-0.528,-0.432,-0.489,0.543,-0.015,-0.004,0.006,...,-0.482,-0.407,0.523,0.004,-0.003,-0.022,0.008,-0.002,0.003,0.000
2398,0.000,0.000,0.000,-0.528,-0.431,-0.489,0.544,-0.062,-0.006,0.001,...,-0.467,-0.416,0.520,0.005,0.003,-0.033,-0.009,0.006,-0.006,-0.003
2399,0.000,0.000,0.000,-0.528,-0.432,-0.489,0.544,-0.064,-0.006,0.004,...,-0.465,-0.407,0.521,0.008,0.006,-0.038,-0.030,0.005,0.002,0.001

In [ ]:
stop_90_diff.to_csv('stop_90_diff_quat.csv', index=False, header=True)
forward_90_diff.to_csv('0_90_diff_quat.csv', index=False, header=True)
left_90_diff.to_csv('90_90_diff_quat.csv', index=False, header=True)
backward_90_diff.to_csv('180_90_diff_quat.csv', index=False, header=True)
right_90_diff.to_csv('270_90_diff_quat.csv', index=False, header=True)

In [ ]:
stop_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
frente_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
direita_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
stop_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")