In [44]:
from pathlib import Path
import numpy as np
import pandas as pd

In [45]:
stop_90 = pd.read_csv('data/stop_90_quat.csv', sep=",")
stop_90_without_speed = stop_90
stop_90_without_speed

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,-0.199,0.634,0.189,-0.095,0.553,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.127,-0.027,2.241,0.199,0.037,-0.025,-0.004,0.999
1,-0.199,0.635,0.189,-0.095,0.552,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.033,2.242,0.199,0.030,-0.027,0.001,0.999
2,-0.199,0.634,0.189,-0.095,0.552,0.805,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.038,2.242,0.198,0.030,-0.033,0.003,0.999
3,-0.199,0.634,0.189,-0.095,0.552,0.805,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.041,2.241,0.197,0.031,-0.035,0.006,0.999
4,-0.199,0.635,0.189,-0.095,0.552,0.804,0.196,0.141,0.622,0.237,...,-0.556,-0.821,0.128,-0.039,2.241,0.197,0.028,-0.037,0.002,0.999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,-0.049,0.616,-0.114,-0.634,0.404,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.410,-0.072,2.132,-0.012,0.012,0.926,-0.045,-0.375
4796,-0.048,0.616,-0.114,-0.633,0.405,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.069,2.133,-0.014,0.016,0.931,-0.047,-0.363
4797,-0.048,0.616,-0.114,-0.632,0.407,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.064,2.133,-0.018,0.018,0.944,-0.049,-0.324
4798,-0.048,0.616,-0.115,-0.632,0.408,0.345,0.562,-0.108,0.623,0.224,...,0.574,0.593,0.411,-0.055,2.133,-0.024,0.030,0.961,-0.052,-0.271
4799,-0.048,0.616,-0.115,-0.632,0.408,0.345,0.562,-0.108,0.623,0.224,...,0.575,0.593,0.411,-0.045,2.133,-0.030,0.039,0.975,-0.048,-0.212

In [46]:
euler=stop_90[['e_r_x','e_r_y','e_r_z','e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
euler

      e_r_x  e_r_y  e_r_z  e_r_w  d_r_x  d_r_y  d_r_z  d_r_w
0    -0.095  0.553  0.804  0.196 -0.032 -0.556 -0.821  0.127
1    -0.095  0.552  0.804  0.196 -0.032 -0.556 -0.821  0.128
2    -0.095  0.552  0.805  0.196 -0.032 -0.556 -0.821  0.128
3    -0.095  0.552  0.805  0.196 -0.032 -0.556 -0.821  0.128
4    -0.095  0.552  0.804  0.196 -0.031 -0.556 -0.821  0.128
...     ...    ...    ...    ...    ...    ...    ...    ...
4795 -0.634  0.404  0.345  0.562 -0.387  0.575  0.593  0.410
4796 -0.633  0.405  0.345  0.562 -0.387  0.575  0.593  0.411
4797 -0.632  0.407  0.345  0.562 -0.387  0.575  0.593  0.411
4798 -0.632  0.408  0.345  0.562 -0.387  0.574  0.593  0.411
4799 -0.632  0.408  0.345  0.562 -0.387  0.575  0.593  0.411

[4800 rows x 8 columns]

In [47]:
stop_90_diff = stop_90_without_speed.diff()
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.001,0.000,0.000,-0.001,0.000,0.0,0.000,0.0,0.0,...,0.000,0.0,0.001,-0.006,0.001,0.000,-0.007,-0.002,0.005,0.000
2,0.000,-0.001,0.000,0.000,0.000,0.001,0.0,0.000,0.0,0.0,...,0.000,0.0,0.000,-0.005,0.000,-0.001,0.000,-0.006,0.002,0.000
3,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.0,...,0.000,0.0,0.000,-0.003,-0.001,-0.001,0.001,-0.002,0.003,0.000
4,0.000,0.001,0.000,0.000,0.000,-0.001,0.0,0.000,0.0,0.0,...,0.000,0.0,0.000,0.002,0.000,0.000,-0.003,-0.002,-0.004,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.000,0.000,0.000,0.000,0.001,0.000,0.0,0.001,0.0,0.0,...,0.000,0.0,0.000,0.002,0.000,-0.001,0.002,0.004,0.000,0.009
4796,0.001,0.000,0.000,0.001,0.001,0.000,0.0,0.000,0.0,0.0,...,0.000,0.0,0.001,0.003,0.001,-0.002,0.004,0.005,-0.002,0.012
4797,0.000,0.000,0.000,0.001,0.002,0.000,0.0,0.000,0.0,0.0,...,0.000,0.0,0.000,0.005,0.000,-0.004,0.002,0.013,-0.002,0.039
4798,0.000,0.000,-0.001,0.000,0.001,0.000,0.0,0.000,0.0,0.0,...,-0.001,0.0,0.000,0.009,0.000,-0.006,0.012,0.017,-0.003,0.053
4799,0.000,0.000,0.000,0.000,0.000,0.000,0.0,0.000,0.0,0.0,...,0.001,0.0,0.000,0.010,0.000,-0.006,0.009,0.014,0.004,0.059

In [48]:
stop_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.095,0.553,0.804,0.196,NaN,NaN,NaN,...,-0.556,-0.821,0.127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.001,0.000,-0.095,0.552,0.804,0.196,0.000,0.0,0.0,...,-0.556,-0.821,0.128,-0.006,0.001,0.000,-0.007,-0.002,0.005,0.000
2,0.000,-0.001,0.000,-0.095,0.552,0.805,0.196,0.000,0.0,0.0,...,-0.556,-0.821,0.128,-0.005,0.000,-0.001,0.000,-0.006,0.002,0.000
3,0.000,0.000,0.000,-0.095,0.552,0.805,0.196,0.000,0.0,0.0,...,-0.556,-0.821,0.128,-0.003,-0.001,-0.001,0.001,-0.002,0.003,0.000
4,0.000,0.001,0.000,-0.095,0.552,0.804,0.196,0.000,0.0,0.0,...,-0.556,-0.821,0.128,0.002,0.000,0.000,-0.003,-0.002,-0.004,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.000,0.000,0.000,-0.634,0.404,0.345,0.562,0.001,0.0,0.0,...,0.575,0.593,0.410,0.002,0.000,-0.001,0.002,0.004,0.000,0.009
4796,0.001,0.000,0.000,-0.633,0.405,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.003,0.001,-0.002,0.004,0.005,-0.002,0.012
4797,0.000,0.000,0.000,-0.632,0.407,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.005,0.000,-0.004,0.002,0.013,-0.002,0.039
4798,0.000,0.000,-0.001,-0.632,0.408,0.345,0.562,0.000,0.0,0.0,...,0.574,0.593,0.411,0.009,0.000,-0.006,0.012,0.017,-0.003,0.053
4799,0.000,0.000,0.000,-0.632,0.408,0.345,0.562,0.000,0.0,0.0,...,0.575,0.593,0.411,0.010,0.000,-0.006,0.009,0.014,0.004,0.059

In [49]:
forward_90 = pd.read_csv('data/0_90_quat.csv', sep=",")
forward_90_without_speed = forward_90[forward_90.columns[:-1]]
euler_forward_90=forward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
forward_90_diff = forward_90_without_speed.diff()
forward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x', 'd_r_y', 'd_r_z', 'd_r_w']]=euler_forward_90
forward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,d_r_x,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z
0,NaN,NaN,NaN,-0.125,0.559,0.788,0.224,NaN,NaN,NaN,-0.089,-0.554,-0.809,0.174,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.005,-0.001,0.001,0.002,0.004,-0.009
2,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.007,-0.001,0.001,0.001,0.006,-0.010
3,0.000,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,0.004,0.001,0.001,-0.003,0.001,0.004
4,0.001,0.000,0.000,-0.125,0.559,0.788,0.224,0.000,0.000,0.000,-0.089,-0.554,-0.809,0.175,-0.001,0.001,-0.001,-0.004,-0.005,0.008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.000,0.000,0.000,0.016,-0.703,-0.709,0.048,-0.001,0.007,0.041,0.105,0.728,0.676,0.035,0.022,-0.001,0.009,0.008,-0.009,0.009
4796,0.000,0.000,0.000,0.015,-0.703,-0.709,0.048,0.000,-0.013,-0.058,0.064,0.730,0.678,0.051,0.039,-0.001,0.004,0.016,-0.004,-0.007
4797,0.000,0.000,0.000,0.014,-0.703,-0.709,0.049,0.020,-0.017,-0.097,0.068,0.714,0.696,0.015,0.041,0.002,0.001,-0.010,-0.003,-0.013
4798,0.000,0.001,0.000,0.014,-0.704,-0.709,0.049,0.012,-0.009,-0.085,-0.070,-0.706,-0.704,0.002,0.040,0.001,0.002,-0.007,-0.001,-0.014
4799,0.000,0.000,-0.001,0.014,-0.704,-0.708,0.049,0.004,-0.006,-0.063,-0.085,-0.707,-0.702,0.001,0.048,0.000,0.002,-0.003,0.002,-0.014

In [50]:
left_90 = pd.read_csv('data/90_90_quat.csv', sep=",")
left_90_without_speed =left_90
euler_left_90=left_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
left_90_diff =left_90_without_speed.diff()
left_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_left_90
left_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,0.018,0.632,0.761,0.148,NaN,NaN,NaN,...,-0.554,-0.822,0.127,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.022,-0.015,-0.069,-0.002,0.611,0.775,0.160,-0.001,0.000,0.001,...,-0.550,-0.825,0.128,-0.039,-0.002,0.022,0.008,-0.001,0.014,0.000
2,0.001,-0.021,-0.123,0.008,0.593,0.797,0.110,0.001,0.000,0.001,...,-0.548,-0.826,0.130,-0.039,0.000,0.007,-0.001,0.006,0.005,0.000
3,0.001,-0.010,-0.120,0.018,0.565,0.816,0.123,-0.001,-0.002,0.000,...,-0.544,-0.828,0.132,-0.037,-0.008,-0.003,0.021,0.006,0.005,0.001
4,0.004,-0.003,-0.080,-0.006,0.571,0.807,0.150,0.005,-0.001,0.001,...,-0.511,-0.846,0.145,-0.051,-0.006,-0.019,-0.011,0.007,0.003,0.000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,-0.085,0.004,-0.014,-0.501,0.577,0.440,0.471,-0.001,0.000,0.000,...,0.563,0.591,0.433,-0.009,0.000,-0.015,-0.004,0.001,-0.007,0.001
4796,0.000,-0.005,0.012,-0.469,0.584,0.491,0.444,0.000,-0.001,0.000,...,0.563,0.591,0.432,-0.011,-0.002,-0.025,0.005,0.010,0.011,0.010
4797,0.077,-0.012,-0.002,-0.485,0.552,0.509,0.449,0.000,0.001,0.000,...,0.563,0.591,0.433,-0.002,0.000,-0.031,-0.002,0.005,0.034,0.010
4798,0.076,-0.008,-0.006,-0.521,0.531,0.493,0.452,0.001,0.000,0.001,...,0.562,0.591,0.433,0.000,0.001,-0.031,-0.017,0.004,0.027,0.009
4799,0.078,-0.007,0.012,-0.504,0.553,0.512,0.421,0.000,0.000,0.000,...,0.561,0.592,0.435,-0.001,0.000,-0.046,-0.031,0.001,0.041,0.007

In [51]:
backward_90 = pd.read_csv('data/180_90_quat.csv', sep=",")
backward_90_without_speed = backward_90
euler_backward_90=backward_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
backward_90_diff = backward_90_without_speed.diff()
backward_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_backward_90
backward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.567,0.292,0.623,0.453,NaN,NaN,NaN,...,0.516,0.657,0.260,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.034,0.023,0.005,-0.568,0.094,0.705,0.414,-0.003,0.000,0.002,...,0.514,0.658,0.257,0.023,-0.001,0.020,0.004,0.012,-0.001,0.013
2,-0.133,0.018,0.016,-0.564,0.241,0.622,0.486,-0.001,0.001,0.000,...,0.512,0.659,0.258,0.010,0.007,-0.002,-0.005,-0.005,0.009,-0.005
3,-0.150,0.023,-0.032,-0.552,0.293,0.512,0.590,0.000,0.000,0.000,...,0.514,0.657,0.257,-0.001,0.000,-0.010,-0.008,0.000,0.000,0.000
4,-0.065,0.012,0.006,-0.503,0.360,0.525,0.584,0.000,-0.001,0.000,...,0.513,0.659,0.254,-0.010,-0.001,-0.015,-0.011,0.003,-0.001,0.003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,-0.021,0.013,-0.097,-0.713,0.135,0.049,0.686,0.000,0.001,0.000,...,0.098,0.153,0.690,0.001,0.003,0.002,-0.029,0.003,0.019,-0.010
4796,0.001,0.009,-0.083,-0.682,0.126,0.016,0.720,-0.001,-0.001,0.000,...,0.098,0.152,0.690,0.010,0.000,-0.008,-0.013,0.003,0.021,-0.018
4797,0.007,0.001,-0.015,-0.684,0.124,0.007,0.719,0.001,0.000,0.000,...,0.098,0.152,0.689,0.017,0.001,-0.011,-0.014,0.001,0.001,-0.015
4798,0.020,-0.014,0.051,-0.713,0.109,-0.008,0.693,0.000,0.001,0.000,...,0.097,0.152,0.689,0.031,-0.002,-0.009,0.003,-0.001,-0.018,-0.010
4799,0.013,-0.007,0.079,-0.728,0.107,0.024,0.677,-0.001,0.000,0.000,...,0.097,0.152,0.689,0.032,0.002,-0.006,0.018,0.000,-0.005,-0.009

In [52]:
right_90 = pd.read_csv('data/270_90_quat.csv', sep=",")
right_90_without_speed = right_90
euler_right_90=right_90[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]
right_90_diff = right_90_without_speed.diff()
right_90_diff[['e_r_x','e_r_y','e_r_z', 'e_r_w', 'd_r_x','d_r_y','d_r_z','d_r_w']]=euler_right_90
right_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,d_t_x,d_t_y,d_t_z,...,d_r_y,d_r_z,d_r_w,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,-0.793,-0.163,-0.020,0.587,NaN,NaN,NaN,...,0.234,0.166,0.481,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-0.010,-0.012,0.112,-0.810,-0.153,0.005,0.566,0.000,-0.001,0.001,...,0.234,0.174,0.477,0.030,0.005,0.020,0.003,0.000,0.000,-0.003
2,-0.016,-0.002,0.105,-0.825,-0.133,0.032,0.548,-0.001,-0.001,0.001,...,0.225,0.171,0.464,0.024,0.007,0.037,0.003,0.000,0.000,-0.010
3,-0.004,-0.004,0.034,-0.802,-0.153,0.042,0.576,-0.001,-0.003,0.000,...,0.193,0.137,0.396,0.018,-0.001,0.042,0.007,0.000,0.010,-0.016
4,0.002,0.001,-0.001,-0.821,-0.144,0.044,0.551,-0.019,0.028,-0.076,...,0.165,0.094,0.283,0.007,0.015,0.019,0.018,0.000,-0.002,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4795,0.000,0.000,0.000,-0.526,-0.432,-0.490,0.545,0.092,0.012,-0.007,...,-0.455,-0.404,0.524,-0.003,0.003,-0.007,-0.006,0.001,0.018,-0.001
4796,0.000,0.000,0.000,-0.528,-0.432,-0.489,0.543,0.085,0.006,-0.006,...,-0.499,-0.350,0.531,0.002,-0.004,-0.013,0.013,-0.009,0.005,0.005
4797,-0.001,-0.001,0.000,-0.528,-0.432,-0.489,0.543,-0.015,-0.004,0.006,...,-0.482,-0.407,0.523,0.004,-0.003,-0.022,0.008,-0.002,0.003,0.000
4798,0.000,0.000,0.000,-0.528,-0.431,-0.489,0.544,-0.062,-0.006,0.001,...,-0.467,-0.416,0.520,0.005,0.003,-0.033,-0.009,0.006,-0.006,-0.003
4799,0.000,0.000,0.000,-0.528,-0.432,-0.489,0.544,-0.064,-0.006,0.004,...,-0.465,-0.407,0.521,0.008,0.006,-0.038,-0.030,0.005,0.002,0.001

In [53]:
# stop = stop_passado.append(stop_90_diff, ignore_index=True)
# forward = frente_passado.append(forward_90_diff, ignore_index=True)
# left = esquerda_passado.append(left_90_diff, ignore_index=True)
# backward = tras_passado.append(backward_90_diff, ignore_index=True)
# right = direita_passado.append(right_90_diff, ignore_index=True)

In [54]:
# stop_passado = pd.read_csv('data/stop_90_diff_quat.csv', sep=",")
# frente_passado = pd.read_csv('data/0_90_diff_quat.csv', sep=",")
# esquerda_passado = pd.read_csv('data/90_90_diff_quat.csv', sep=",")
# tras_passado = pd.read_csv('data/180_90_diff_quat.csv', sep=",")
# direita_passado = pd.read_csv('data/270_90_diff_quat.csv', sep=",")

In [55]:
# stop = stop_passado.append(stop_90_diff, ignore_index=True)
# forward = frente_passado.append(forward_90_diff, ignore_index=True)
# left = esquerda_passado.append(left_90_diff, ignore_index=True)
# backward = tras_passado.append(backward_90_diff, ignore_index=True)
# right = direita_passado.append(right_90_diff, ignore_index=True)

In [56]:
# stop.to_csv('stop_90_diff_quat.csv', index=False, header=True)
# forward.to_csv('0_90_diff_quat.csv', index=False, header=True)
# left.to_csv('90_90_diff_quat.csv', index=False, header=True)
# backward.to_csv('180_90_diff_quat.csv', index=False, header=True)
# right.to_csv('270_90_diff_quat.csv', index=False, header=True)

In [57]:
stop_90_diff.to_csv('data/stop_90_diff_quat.csv', index=False, header=True)
forward_90_diff.to_csv('data/0_90_diff_quat.csv', index=False, header=True)
left_90_diff.to_csv('data/90_90_diff_quat.csv', index=False, header=True)
backward_90_diff.to_csv('data/180_90_diff_quat.csv', index=False, header=True)
right_90_diff.to_csv('data/270_90_diff_quat.csv', index=False, header=True)