In [1]:
from pathlib import Path
import numpy as np
import pandas as pd

In [8]:
stop_90

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w,speed
0,-0.001,0.0,0.0,0.0,0.001,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.000,0.0,stopped
1,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,stopped
2,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,-0.000000,0.000000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0,stopped
3,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,stopped
4,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,-0.000000,0.000000,0.000,0.000,0.001,0.000,0.000,0.001,0.0,stopped
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,stopped
71984,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,stopped
71985,0.000,0.0,-0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,0.000688,269.998625,0.000,0.000,0.000,0.000,-0.002,0.001,0.0,stopped
71986,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0,stopped
71987,0.000,0.0,-0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,0.006990,270.014213,0.002,-0.001,0.001,0.000,0.000,0.000,0.0,stopped

In [15]:
stop_90 = pd.read_csv('data/stop_90_euler.csv', sep=",")
stop_90_without_speed = stop_90[stop_90.columns[:-1]]
stop_90_without_speed

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,-0.001,0.0,0.0,0.0,0.001,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.000,0.0
1,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
4,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71984,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,-0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,-0.001375,0.000688,269.998625,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,-0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71987,0.000,0.0,-0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,-0.013298,0.006990,270.014213,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [16]:
euler=stop_90[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]
euler

,e_r_x_euler,e_r_y_euler,e_r_z_euler,d_r_x_euler,d_r_y_euler,d_r_z_euler
0,0.0,0.0,0.0,0.000000,0.000000,0.000000
1,0.0,0.0,0.0,0.000000,0.000000,0.000000
2,0.0,0.0,0.0,0.000000,-0.000000,0.000000
3,0.0,0.0,0.0,0.000000,0.000000,0.000000
4,0.0,0.0,0.0,0.000000,-0.000000,0.000000
...,...,...,...,...,...,...
71983,0.0,0.0,270.0,0.000000,0.000000,270.000000
71984,0.0,0.0,270.0,0.000000,0.000000,270.000000
71985,0.0,-0.0,270.0,-0.001375,0.000688,269.998625
71986,0.0,0.0,270.0,0.000000,0.000000,270.000000
71987,0.0,-0.0,270.0,-0.013298,0.006990,270.014213

In [17]:
stop_90_diff = stop_90_without_speed.diff()
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.001,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,-0.001,0.001,0.000,-0.001,0.0
4,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000115,0.000000,0.000000,0.005,0.000,0.000,-0.001,0.001,-0.002,0.0
71984,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,0.0,...,-0.001375,0.000688,-0.001375,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,0.0,0.0,0.001,0.0,0.0,0.0,0.0,0.0,...,0.001375,-0.000688,0.001375,0.000,0.000,0.000,0.000,0.002,-0.001,0.0
71987,0.000,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,0.0,...,-0.013298,0.006990,0.014213,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [18]:
stop_90_diff[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]=euler
stop_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.001,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,0.000,0.0
2,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,-0.001,0.000,0.001,0.0
3,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000,0.000,-0.001,0.001,0.000,-0.001,0.0
4,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,0.0,...,0.000000,-0.000000,0.000000,0.000,0.000,0.001,0.000,0.000,0.001,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
71983,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.005,0.000,0.000,-0.001,0.001,-0.002,0.0
71984,0.000,0.0,0.0,0.0,0.000,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.0
71985,0.000,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,-0.001375,0.000688,269.998625,0.000,0.000,0.000,0.000,-0.002,0.001,0.0
71986,0.000,0.0,0.0,0.0,0.001,0.0,0.0,0.0,0.0,270.0,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.002,-0.001,0.0
71987,0.000,0.0,0.0,0.0,-0.001,0.0,0.0,0.0,-0.0,270.0,...,-0.013298,0.006990,270.014213,0.002,-0.001,0.001,0.000,0.000,0.000,0.0

In [27]:
forward_90 = pd.read_csv('data/0_90_euler.csv', sep=",")
forward_90_without_speed = forward_90[forward_90.columns[:-1]]
euler_forward_90=forward_90[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]
forward_90_diff = forward_90_without_speed.diff()
forward_90_diff[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]=euler_forward_90
forward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,-0.000115,...,0.000000,-0.000000,0.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.001,0.001,-0.002,0.001,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.000,0.000,-0.001,0.000,0.000,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,0.001,0.000,0.001,0.000,0.000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,-0.003,-0.001,0.003,-0.001,0.006,-0.006,-0.011,-0.003438,0.003438,-0.002865,...,0.000000,-0.000229,0.000000,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,0.002,0.003,0.016,0.000,-0.006,0.005,-0.005,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,0.001,0.000,-0.006,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,0.004013,...,-0.055529,0.045837,-0.050504,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,-0.001,0.000,0.006,0.002,0.012,-0.011,-0.001,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,0.000344,...,-0.015823,0.046983,-0.024429,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [28]:
left_90 = pd.read_csv('data/90_90_euler.csv', sep=",")
left_90_without_speed =left_90[left_90.columns[:-1]]
euler_left_90=left_90[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]
left_90_diff =left_90_without_speed.diff()
left_90_diff[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]=euler_left_90
left_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,89.999885,...,0.000000,-0.000000,90.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.001,0.001,-0.002,0.001,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,-0.001,0.000,0.000,0.000,0.001,0.000,0.000,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,-0.003,-0.001,-0.003,-0.001,0.006,-0.006,-0.011,-0.003438,0.003438,89.997135,...,0.000000,-0.000229,90.000000,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,-0.016,0.003,0.002,0.000,-0.006,0.005,-0.005,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,0.006,0.000,0.001,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,90.004013,...,-0.055529,0.045837,89.949496,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,-0.006,0.000,-0.001,0.002,0.012,-0.011,-0.001,0.000000,0.000000,90.000000,...,0.000000,0.000000,90.000000,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,90.000344,...,-0.015823,0.046983,89.975571,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [30]:
backward_90 = pd.read_csv('data/180_90_euler.csv', sep=",")
backward_90_without_speed = backward_90[backward_90.columns[:-1]]
euler_backward_90=backward_90[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]
backward_90_diff = backward_90_without_speed.diff()
backward_90_diff[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]=euler_backward_90
backward_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,179.999885,...,0.000000,-0.000000,180.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.001,0.001,-0.002,0.001,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,0.000,0.000,0.001,0.000,0.000,0.000,0.000,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.000,0.000,-0.001,0.000,0.001,0.000,0.000,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,0.003,-0.001,-0.003,-0.001,0.006,-0.006,-0.011,-0.003438,0.003438,179.997135,...,0.000000,-0.000229,180.000000,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,-0.002,0.003,-0.016,0.000,-0.006,0.005,-0.005,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,-0.001,0.000,0.006,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,180.004013,...,-0.055529,0.045837,179.949496,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,0.001,0.000,-0.006,0.002,0.012,-0.011,-0.001,0.000000,0.000000,180.000000,...,0.000000,0.000000,180.000000,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,180.000344,...,-0.015823,0.046983,179.975571,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [31]:
right_90 = pd.read_csv('data/270_90_euler.csv', sep=",")
right_90_without_speed = right_90[right_90.columns[:-1]]
euler_right_90=right_90[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]
right_90_diff = right_90_without_speed.diff()
right_90_diff[['e_r_x_euler','e_r_y_euler','e_r_z_euler', 'd_r_x_euler','d_r_y_euler','d_r_z_euler']]=euler_right_90
right_90_diff

,e_t_x,e_t_y,e_t_z,e_r_x,e_r_y,e_r_z,e_r_w,e_r_x_euler,e_r_y_euler,e_r_z_euler,...,d_r_x_euler,d_r_y_euler,d_r_z_euler,c_t_x,c_t_y,c_t_z,c_r_x,c_r_y,c_r_z,c_r_w
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.000,0.000,0.000,-0.001,-0.001,0.002,-0.001,-0.000115,0.000344,269.999885,...,0.000000,-0.000000,270.000000,0.000,0.000,0.000,-0.001,0.000,-0.001,0.000
2,0.000,0.000,0.000,0.001,0.001,-0.002,0.001,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.001,0.000,0.001,0.000
3,-0.001,0.000,0.000,0.000,0.000,0.000,0.000,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.000
4,0.001,0.000,0.000,0.000,0.001,0.000,0.000,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,0.000,0.000,0.000,0.000,0.000,0.000,0.001
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23992,0.003,-0.001,0.003,-0.001,0.006,-0.006,-0.011,-0.003438,0.003438,269.997135,...,0.000000,-0.000229,270.000000,0.001,-0.001,-0.002,-0.004,0.005,-0.001,0.000
23993,0.016,0.003,-0.002,0.000,-0.006,0.005,-0.005,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,0.003,-0.001,0.001,0.002,-0.004,0.002,0.000
23994,-0.006,0.000,-0.001,-0.002,-0.012,0.011,0.001,-0.015360,0.001146,270.004013,...,-0.055529,0.045837,269.949496,-0.004,0.000,-0.008,0.001,0.000,-0.001,0.000
23995,0.006,0.000,0.001,0.002,0.012,-0.011,-0.001,0.000000,0.000000,270.000000,...,0.000000,0.000000,270.000000,0.004,0.000,0.008,-0.001,0.000,0.001,0.000
23996,0.000,0.000,0.000,0.000,0.003,-0.003,-0.001,-0.001031,-0.000344,270.000344,...,-0.015823,0.046983,269.975571,0.002,0.001,0.001,-0.004,-0.002,0.005,0.001

In [32]:
stop_90_diff.to_csv('stop_90_diff_euler.csv', index=False, header=True)
forward_90_diff.to_csv('0_90_diff_euler.csv', index=False, header=True)
left_90_diff.to_csv('90_90_diff_euler.csv', index=False, header=True)
backward_90_diff.to_csv('180_90_diff_euler.csv', index=False, header=True)
right_90_diff.to_csv('270_90_diff_euler.csv', index=False, header=True)

In [33]:
for i in stop_90_diff:
    print(i)

e_t_x
e_t_y
e_t_z
e_r_x
e_r_y
e_r_z
e_r_w
e_r_x_euler
e_r_y_euler
e_r_z_euler
d_t_x
d_t_y
d_t_z
d_r_x
d_r_y
d_r_z
d_r_w
d_r_x_euler
d_r_y_euler
d_r_z_euler
c_t_x
c_t_y
c_t_z
c_r_x
c_r_y
c_r_z
c_r_w